name: tests
on:
  push:
    paths-ignore:
      - "doc/**"
      - "README.md"
      - ".gitignore"
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v1
        with:
          version: v1.29

      - name: tests
        run: |
          go test -race -v ./...
